version: 2.1

# Define executors
executors:
  macos-executor:
    macos:
      xcode: "15.4"  # Latest stable Xcode for macOS Sonoma
    resource_class: macos.m1.medium.gen1
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

# Define jobs
jobs:
  build-and-test:
    executor: macos-executor
    steps:
      - checkout
      
      # Cache Gradle dependencies
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-v1-{{ checksum "build.gradle" }}
            - gradle-cache-v1-
      
      # Cache Gradle wrapper
      - restore_cache:
          keys:
            - gradle-wrapper-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-wrapper-v1-
      
      # Install Oracle Java 23 (CircleCI macOS comes with older Java versions)
      - run:
          name: Install Oracle Java 23
          command: |
            # Download Oracle JDK 23 for macOS ARM64
            curl -L -o jdk-23_macos-aarch64_bin.tar.gz "https://download.oracle.com/java/23/archive/jdk-23.0.1_macos-aarch64_bin.tar.gz"
            tar -xzf jdk-23_macos-aarch64_bin.tar.gz
            sudo mv jdk-23.0.1.jdk /Library/Java/JavaVirtualMachines/
            echo 'export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-23.0.1.jdk/Contents/Home' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            # Verify installation
            java -version
            javac -version
      
      # Make Gradle wrapper executable
      - run:
          name: Make Gradle wrapper executable
          command: chmod +x ./gradlew
      
      # Run Spotless check (code formatting)
      - run:
          name: Code formatting check
          command: ./gradlew spotlessCheck
      
      # Run tests
      - run:
          name: Run tests
          command: ./gradlew test
      
      # Build .app bundle
      - run:
          name: Build macOS .app bundle
          command: ./gradlew packageMacApp
      
      # Build DMG installer
      - run:
          name: Build DMG installer
          command: ./gradlew packageMacDmg
      
      # Store test results
      - store_test_results:
          path: build/test-results/test
      
      # Store test reports
      - store_artifacts:
          path: build/reports/tests/test
          destination: test-reports
      
      # Store DMG as artifact
      - store_artifacts:
          path: tmp/mac/Penn TotalRecall-1.0.0.dmg
          destination: Penn TotalRecall-1.0.0.dmg
      
      # Store Gradle cache
      - save_cache:
          key: gradle-cache-v1-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      
      # Store Gradle wrapper cache
      - save_cache:
          key: gradle-wrapper-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - gradle/wrapper

# Define workflows
workflows:
  version: 2
  build-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
                - /feature\/.*/
                - /hotfix\/.*/