package components.preferences;

import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.AbstractAction;
import util.GiveMessage;

/** Restores all preferences to their factory defaults. */
public class RestoreDefaultsAction extends AbstractAction {

    /**
     * Recurses through all <code>AbstractPreferenceDisplays</code>, and restores them to their
     * defaults. Afterward notifies user of success and hides the <code>PreferencesFrame</code>.
     *
     * @param e The <code>ActionEvent</code> generated by the trigger
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        List<AbstractPreferenceDisplay> allPrefs =
                PreferencesFrame.getInstance().getAbstractPreferences();
        for (int i = 0; i < allPrefs.size(); i++) {
            allPrefs.get(i).restoreDefault();
        }
        GiveMessage.infoMessage("All preferences successfully restored to defaults.");

        // safer than directly using setVisible(false), since this double checks the assumption that
        // all preferences are saved
        PreferencesFrame.getInstance()
                .windowClosing(
                        new WindowEvent(
                                PreferencesFrame.getInstance(), WindowEvent.WINDOW_CLOSING));
    }
}
