name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15
    env:
      GRADLE_OPTS: "-Dorg.gradle.workers.max=5 -Dorg.gradle.parallel=true -Dorg.gradle.caching=false -Dorg.gradle.configuration-cache=false"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Accept Xcode license
      run: sudo xcodebuild -license accept
      
    - name: Set up Java 24 EA
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24-ea'
        
    - name: Cache Gradle dependencies only
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/modules-2
          ~/.gradle/wrapper
        key: gradle-deps-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-deps-${{ runner.os }}-
          
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew check --rerun-tasks
      env:
        CI: true
    
    - name: Package Mac DMG
      run: ./gradlew packageMacDmg
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/test-results/test/
          build/test-results/packageTest/
          build/test-results/audioTest/
        retention-days: 30
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          build/reports/tests/test/
          build/reports/tests/packageTest/
          build/reports/tests/audioTest/
        retention-days: 30
        
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: build/packaging/mac/*.dmg
        retention-days: 90